# Generated by Django 4.2.11 on 2024-05-05 18:15

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('eventBlog', '0004_event_resized_poster_alter_event_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='seats_available',
            field=models.IntegerField(default=0, null=True, verbose_name='Number of seats available'),
        ),
        migrations.AddField(
            model_name='event',
            name='seats_taken',
            field=models.IntegerField(default=0, verbose_name='Number of seats taken'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='resized_poster',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[640, 360], upload_to='resized_image', verbose_name='Resized Poster (16:9 only)'),
        ),
    ]
