# Generated by Django 4.2.11 on 2024-05-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventBlog', '0005_event_seats_available_event_seats_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='seats_available',
            field=models.IntegerField(default=0, verbose_name='Number of seats available'),
        ),
    ]
