# Generated by Django 4.2.11 on 2024-05-06 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventBlog', '0007_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventBlog.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventBlog.userprofile')),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='events',
            field=models.ManyToManyField(related_name='visitors', through='eventBlog.UserEvent', to='eventBlog.event'),
        ),
    ]
