# Generated by Django 4.2.11 on 2024-05-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventBlog', '0008_userevent_userprofile_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='events',
            field=models.ManyToManyField(through='eventBlog.UserEvent', to='eventBlog.event'),
        ),
    ]
