# Generated by Django 4.2.11 on 2024-05-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventBlog', '0009_alter_userprofile_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='events',
            field=models.ManyToManyField(related_name='user_events', through='eventBlog.UserEvent', to='eventBlog.event'),
        ),
    ]
