# Generated by Django 4.2.11 on 2024-05-06 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventBlog', '0011_alter_userevent_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userevent',
            unique_together=set(),
        ),
    ]
