# Generated by Django 4.2.11 on 2024-05-07 08:42

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('eventBlog', '0012_alter_userevent_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='resized_poster',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[640, 360], upload_to='resized_image', verbose_name='Poster again (it will be resized)'),
        ),
    ]
